### ISSUE TITLE
Is it possible to increment rate limit on one view and consume on others?

### ISSUE THREAD

**Issue by ryanwilsonperkin** [jsocol/django-ratelimit#111]
I'm looking to use django-ratelimit to increment a rate limit when a user POSTs to a view, and show a notice if the limit has been exceeded, on either a POST *or* a GET. Is this feature supported?

My goal would be something like so:
```python
from django.views.generic import FormView
from ratelimit.mixins import RatelimitMixin

class ExampleView(RatelimitMixin, FormView):
    ratelimit_key = 'ip'
    ratelimit_method = 'POST'
    ratelimit_rate = '3/m'

    def get_context_data(self, **kwargs):
        context = super(ExampleView, self).get_context_data(**kwargs)
        context['limited'] = self.request.limited
```

However, this raises an AttributeError when this view processes a GET, since the `limited` attribute is only applied on `request`s for a POST. I could change `ratelimit_method` to `ALL`, but I *don't* want to increment the counter for GETs.

**Comment by ryanwilsonperkin** [comment]
If this is not a feature, would you be willing to accept a Pull Request for it? One way I believe this could be added, would be to allow `ratelimit.decorators.ratelimit` to accept `increment` as a keyword argument, which could be proxied to `is_ratelimited`.

This way you could do
```python
from ratelimit.decorators import ratelimit

@ratelimit(group='example', increment=True)
def post(request, *args, **kwargs):
    return 'foo'

@ratelimit(group='example', increment=False)
    return 'bar'
```

**Comment by jsocol** [comment]
This can be built with the `is_ratelimited` helper. It's going to be tough with the `RatelimitMixin`, though, which is inherently more limited (they can't be stacked). The decorators do support CBVs, iirc.

In general this is the strategy: the `@ratelimit` decorator should support the 80-90% use-cases and anything beyond that scope can and should be handled with `is_ratelimited`, which gives a lot more flexibility.
