### ISSUE TITLE
No 1.0.1 update in master

### ISSUE THREAD

**Issue by jsocol** [jsocol/django-ratelimit#114]
Hey @adamchainz can you push the commit bumping the version to master and tag it, and update the changelog?

**Comment by adamchainz** [comment]
Sorry, I failed to properly reconfigure my local git so that I pushed them to adamchainz/django-ratelimit rather than jsocol/django-ratelimit. Pushed at 53abd9ad92559aec0723eb00069d858587bf6037 , thanks for spotting

**Comment by jsocol** [comment]
Thanks!
