### ISSUE TITLE
django caches Compatible 

### ISSUE THREAD

**Issue by mymusise** [jsocol/django-ratelimit#115]
Hey, guy~
Is django-ratelimit still compatible with 1.6.x？I got a error `ImportError: cannot import name caches` from utils.py. Just like #60 ，`from django.core.cache import caches` and `caches['cache_name']` not work  in django 1.6.x.

**Comment by jsocol** [comment]
No, 1.6 hasn't been a supported version for a while. Only the "active" versions of Django are supported

**Comment by adamchainz** [comment]
If you read the changelog you'll see it was 1.0.0 that dropped support for Django 1.6: https://github.com/jsocol/django-ratelimit/blob/master/CHANGELOG

Try that, although it is missing a few fixes.

**Comment by mymusise** [comment]
Got it, thanks guys
