### ISSUE TITLE
Dont work uWSGI + Nginx

### ISSUE THREAD

**Issue by eseffair** [jsocol/django-ratelimit#118]
Rate limit dont work in this deployment scenario...Any idea?

**Comment by adamchainz** [comment]
I have used it successfully under uWSGI and Nginx. You need to provide **much** more information in an issue, such as the stacktrace for the errors you're seeing, in order for anyone to help you.

**Comment by jsocol** [comment]
If you still need help, please feel free to re-open with more information!
