### ISSUE TITLE
CBV + multiple ratelimit decorator + dispatch + per site cache

### ISSUE THREAD

**Issue by lechup** [jsocol/django-ratelimit#127]
I'm trying to enable ratelimit on my site. I have problems with actually reatelimiting views, i'm using code like:

```python
@method_decorator(ratelimit(key='ip', rate='3/s', block=True), name='dispatch')
@method_decorator(ratelimit(key='ip', rate='20/m', block=True), name='dispatch')
@method_decorator(ratelimit(key='ip', rate='50/h', block=True), name='dispatch')
@method_decorator(vary_on_headers('X-subdomain'), name='dispatch')
class BaseListView(ListView):
    paginate_by = 100
```

I've enabled CACHE:

```python
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'lechup',
    }
}
```

I've refreshed page 100 times within 1 minute and I still do not get 403 ...

If I set `rate='0/s'`, I'm getting 403 page. Any clues what could be wrong?

**Comment by adamchainz** [comment]
`@method_decorator` makes the decorator applicable to a method, but you're applying it to a class. You need to apply it to the `dispatch` method of your view class.

**Comment by lechup** [comment]
@adamchainz AFAIK there are two ways of using `from django.utils.decorators import method_decorator`

https://docs.djangoproject.com/en/1.11/topics/class-based-views/intro/#decorating-the-class

So I can decorate class, as far as I provide `name` kwarg...

**Comment by adamchainz** [comment]
Oh yeah, sorry, TIL!

**Comment by lechup** [comment]
Hm.. it looks like `The per-site cache` https://docs.djangoproject.com/en/1.11/topics/cache/#the-per-site-cache is the reason why ratelimit decorator is not run django just passes the previous output ommiting processing.

**Comment by adamchainz** [comment]
Aha, of course. You can instead use per-view caching, underneath the ratelimit decorator.

**Comment by jsocol** [comment]
You could also use the [`@never_cache`](https://docs.djangoproject.com/en/1.11/topics/http/decorators/#caching) decorator, to opt this particular view out of the full-site caching. 

Since it sounds like this isn't a ratelimit issue I'm going to go ahead and close it, but please feel free to open new issues if you run into any other strange behavior. Thanks!
