### ISSUE TITLE
How to whitelist bots/IP addresses?

### ISSUE THREAD

**Issue by mlissner** [jsocol/django-ratelimit#133]
I put ratelimits in place last week, and now I'm getting errors from Google that it can't crawl as fast as it wants to, and is getting 429 errors as a result.

The easiest fix would be to have a whitelist of IP addresses that are allowed to crawl. That'd work for partner organizations with static IPs, but according to [Google's support page][google], the Googlebot's IP address changes from time to time, so you are expected to verify it by using the `host` command.

So: is there a way to whitelist Google's IP addresses or to run a custom function for whitelisting? 

I could see an API like this for the simple case:

    @ratelimit(key='ip', rate='100/h', block=True, whitelist=[some-list-of-ip-addresses])

And like this for the hard case of having to verify the crawler:

    @ratelimit(key='ip', rate='100/h', block=True, whitelist=is_whitelisted)

The callable would then look something like this:

    def is_whitelisted(request):
        """Check if the IP is in our list of trusted static IPs or if it's Google."""
        ip = request.get('IP_ADDRESS'))
        if ip in settings['WHITELIST']:
            return True
        # Not in our static whitelist. Is it Google?
        is_google = verify_google_by_hostname(ip)
        return is_google

Is there an easy way to handle this? If not would pull requests be welcome? I might be able to find time to do this, though I know I'll struggle to figure out how to pass the request object to the whitelist callable if we go with this API (I'm no good at making wrappers).

Thoughts?

[google]: https://support.google.com/webmasters/answer/80553?hl=en

**Comment by adamchainz** [comment]
In Python you can always wrap a decorator with your own decorator, something like:

```python
ratelimiter = ratelimit(key='ip', rate='100/h', ...)

def ratelimit_if_whitelisted(view):
    ratelimited_view = ratelimiter(view)
    
    @functools.wraps(view)
    def wrapper(request, *args, **kwargs):
        if is_whitelisted(request):
            return view(request, *args, **kwargs)
        return ratelimited_view(request, *args, **kwargs)

    return wrapper

@ratelimit_if_whitelisted
def my_view(request, user_id):
    return HttpResponse('hi')
```

**Comment by adamchainz** [comment]
In Python you can always wrap a decorator with your own decorator, something like:

```python
ratelimiter = ratelimit(key='ip', rate='100/h', ...)

def ratelimit_if_whitelisted(view):
    ratelimited_view = ratelimiter(view)
    
    @functools.wraps(view)
    def wrapper(request, *args, **kwargs):
        if is_whitelisted(request):
            return view(request, *args, **kwargs)
        return ratelimited_view(request, *args, **kwargs)

    return wrapper

@ratelimit_if_whitelisted
def my_view(request, user_id):
    return HttpResponse('hi')
```

**Comment by mlissner** [comment]
Boy, that looks elegant! I'll give it a shot.

**Comment by mlissner** [comment]
I got this working with your tip, thank you very much. You can see my implementation, which handles Google and Bing in the commit above. 

I flipped the logic a bit so that the whitelist is only checked *after* the throttle has been exceeded, rather than on every view, so that should help with performance.

Thank you again for the help and for the great package.

**Comment by adamchainz** [comment]
Looks nice. Yes your logic makes sense if you're keeping your whitelist in cache keys. As an aside, I'd consider using a model - a key-value check on a DB table is not that much slower than a cache hit, plus it's persistent and you can easily check which IP's / hostnames you're trusting to see if things are working okay.

**Comment by mlissner** [comment]
Actually, since the IPs they use for crawling die fairly regularly, and since I don't expect to be saving too many of them, the one week expiration date from the cache is going to be very convenient. It's true though that the cache is more of a pain to check...
