### ISSUE TITLE
Catch ratelimit exception

### ISSUE THREAD

**Issue by ahsan-ul-haq** [jsocol/django-ratelimit#135]
I am using this package to rate limit one of my views. As the site is very widely used the ratelimit exception is caused many times how can I handle the exception in code 
https://github.com/edx/edx-platform/blob/master/openedx/core/djangoapps/oauth_dispatch/views.py#L89

**Comment by adamchainz** [comment]
I think the documentation is clear enough on this: https://django-ratelimit.readthedocs.io/en/v1.0.0/

You can catch the ratelimit exception yourself
