### ISSUE TITLE
django-ratelimit not working in a RHEL WebServer

### ISSUE THREAD

**Issue by obautista01** [jsocol/django-ratelimit#139]
Hi,

I've been tasked with a script that looks at every incoming packet and blocks if the incoming rate > 50 Requests/s from a given IP. This needs to be done on a rolling window of 60 mins.

I went ahead and installed django-ratelimit in a Linux Web server and executed the script below.
Simultaneously I'm sending a bunch of HTTP GET requests from a different machine (in the same network, NO LB in between) using curl in an infinite loop.

The rate limit script is not doing anything; it executes in a couple of seconds and exits with no error.
No single HTTP request is being blocked.

Any idea of what could I be missing here?
I've been trying different rates like 1/m, 2/m, the result is the same.

--------------------------
#!/usr/bin/python
from ratelimit.decorators import ratelimit

@ratelimit(key='ip', rate='1/m', method='GET', block=True)
def myview(request):
    was_limited = getattr(request, 'limited', False)
    return HttpResponse()
-----------------

Thank you very much!
- Octavio

**Comment by adamchainz** [comment]
What cache backend are you using?

**Comment by jsocol** [comment]
@obautista01 Closing for now, but feel free to reopen if you can provide more information!
