### ISSUE TITLE
Request for usage clarification

### ISSUE THREAD

**Issue by estianross** [jsocol/django-ratelimit#142]
Been going over the documentation and can't figure out if there is a way to do what I need. I need to combine 2 rate limits on a view.

The first seems quite simple as it's just 1 request to the view per ip per sec so the following should be adequate:
 `@ratelimit(key='ip', rate='1/sec')`

The second is trickier and is what I need advice figuring out, it should limit ALL requests to the view regardless of ip or user or auth to 10 requests per sec, is this doable with this package?

**Comment by jsocol** [comment]
Probably the best way would be to stack another `@ratelimit` decorator with a [callable `key` value](https://django-ratelimit.readthedocs.io/en/latest/keys.html#callable-values) and have that callable return the same string, e.g. `key=lambda group, req: 'myroutekey'`
