### ISSUE TITLE
Rate limit on URL parameters?

### ISSUE THREAD

**Issue by phillbaker** [jsocol/django-ratelimit#145]
Thanks for your work on this library!

Parameters captured by Django's URLconf are passed into the view function as parameters, e.g.:

```py
# urls.py
url(regex=r'^user/(?P<username>\w{1,50})/$', view='views.profile_page')

# views.py
def profile_page(request, username=None):
    user = User.objects.get(username=username)
   # ...
```

These parameters are not available on the request object itself (or in `request.{GET,POST,META}`), what would be the recommended approach to rate limit on parameters like the `username` parameter?

**Comment by adamchainz** [comment]
You can access `request.resolver_match.kwargs['username']` https://docs.djangoproject.com/en/2.0/ref/request-response/#django.http.HttpRequest.resolver_match

**Comment by phillbaker** [comment]
Thanks!
