### ISSUE TITLE
Django 2.0 compatibility

### ISSUE THREAD

**Issue by BarnabasSzabolcs** [jsocol/django-ratelimit#146]
user_or_ip uses user.is_authenticated() which is a bool not a function in Django 2.0.

**Comment by adamchainz** [comment]
Not since #136 

I think we are just pending a release, @jsocol ?

**Comment by jsocol** [comment]
Correct, I can get to that next week!

**Comment by adamchainz** [comment]
@jsocol still need that release! Last one was nearly a year ago.

**Comment by adamchainz** [comment]
👈prod

If you want you can make me maintainer on PyPI too and I can do it!

**Comment by jsocol** [comment]
@adamchainz you already are, go for it!

**Comment by jsocol** [comment]
Getting a couple of things added in #125, #156, #159 at least

**Comment by jsocol** [comment]
Released as [version 2.0](https://pypi.org/project/django-ratelimit/2.0.0/), because of the wide swing in Django version support. Thanks all!
