### ISSUE TITLE
How to customize 403 page when user is blacked out

### ISSUE THREAD

**Issue by iloveyo123u1** [jsocol/django-ratelimit#148]
when the user is blacked out,  
The page return **403 Forbidden** 
i want it return **sorry, you are blocked, Please come back after 30 seconds.**

thanks 😀

**Comment by adamchainz** [comment]
Set up handler403 in your root urlconf as per: https://docs.djangoproject.com/en/2.0/topics/http/urls/#error-handling

Then in the view you can do something like:

```py
def handler403(request, exception=None):
    if isinstance(exception, Ratelimited):
        return HttpResponse('Sorry you are blocked', status=429)
    return HttpResponseForbidden('Forbidden')
```

**Comment by adamchainz** [comment]
Actually this is a good candidate for a documentation PR
