### ISSUE TITLE
Does the app spport `rate='20/5m'`?

### ISSUE THREAD

**Issue by keyeMyria** [jsocol/django-ratelimit#160]
Does this app spport 

` @ratelimit(key="ip", rate='20/5m', block=True )`

like [flask-limiter](https://github.com/alisaifee/flask-limiter)
And like
 ` @ratelimit(key="ip", rate='20/5m;100/h', block=True )`
multiple limit rule in one rate, delimited by ";" or other delimiter.

**Comment by jsocol** [comment]
See [the docs chapter](https://django-ratelimit.readthedocs.io/en/latest/rates.html) on *Rates*. tl;dr—yes, to `20/5m`; no to `;`, but you can [stack decorators to implement things like burst limits](https://django-ratelimit.readthedocs.io/en/latest/rates.html).
