### ISSUE TITLE
IPv6 subnet blocking

### ISSUE THREAD

**Issue by whs** [jsocol/django-ratelimit#175]
IPv6 deployments often are given a block of IP, so blocks with the entire IP can be evaded easily.

I've seen a local ISP hand out /64 block and AWS hand out [/56 block](https://docs.aws.amazon.com/vpc/latest/userguide/vpc-ip-addressing.html) for each VPC. Let's Encrypt's Boulder use [/48](https://github.com/letsencrypt/boulder/blob/6f44b8bde7f18ab05f2d3101c3beb1d60f711074/sa/sa.go#L296:6) block for rate limiting.

**Comment by jsocol** [comment]
Ah good point! I think right now this can be handled via callable keys based on your needs. Do you have some kind of API for this in mind? /48 is a large space, but that may be a good guideline.

**Comment by jsocol** [comment]
It would also be interesting to consider how we might enable IPv4 subnet blocking. I still don't have a great API for this, but to brainstorm some ideas...

```py
@ratelimit(key='ip/24/48')  # would probably require v4 netmask length
def f(r): pass

@ratelimit(key=ips(v4=24, v6=48))  # could return a callable, param names not great
def f(r): pass

@ratelimit(key=ips(v6=48))  # defaults to v4=32
def f(r): pass

@ratelimit(key=ips(v6='/48'))  # slightly clearer value but not param name
def f(r): pass

@ratelimit(key=netmasks(v4=24, v6=48))
def f(r): pass

@ratelimit(key=subnets(v4=24, v6=48))
def f(r): pass

@ratelimit(key=ip_or_subnet(v6=48))
def f(r): pass

@ratelimit(key='subnet/24/48')
def f(r): pass

@ratelimit(key='subnet4/24')
@ratelimit(key='subnet6/48')
def f(r): pass
```

This does also get complicated when you want to use `user_or_ip`—how could we extend it to expose these more flexible capabilities?
