### ISSUE TITLE
[Docs] More information on using the `is_ratelimited` function

### ISSUE THREAD

**Issue by ibolit** [jsocol/django-ratelimit#177]
Currently, the docs about the `is_ratelimited` function are quite vague: all they say is "sometimes the mixin is not flexible enough, but you can use the `is_ratelimited` function. I couldn't figure out how.

Basically, I want to write my own mixin derived from the `RatelimitMixin` with two rates, like `5/m` and `15/h`, but currently I can't understand how to do that.

**Comment by adamchainz** [comment]
I think you'll want to call `is_ratelimited` twice, once with each of the rates.

**Comment by jsocol** [comment]
This is exactly why the Mixin is deprecated, it can’t do something (multiple limits) that the decorator can do trivially. 

You could write your own version of the mixin, and @adamchainz is right, you’d need to call `is_ratelimited` twice. Or instead you could [use the decorator on the CBV](https://django-ratelimit.readthedocs.io/en/stable/usage.html#class-based-views). (The latest code on GitHub will probably work better than what’s released, and _should_ be stable, but obviously it is still unreleased.)

If there are fairly generic things we can add to the utility docs, I’m open to that (or maybe in the new “Recipes” section). But the point is that we don’t know what people are going to need to do, so I’m not sure what kind of things we can add that would help everyone in the “outside the 95%” use case.

**Comment by ibolit** [comment]
Thank you for your prompt reply. 
I ended up writing my own mixin which adds a number of decorators to the `dispatch` method. 
I can make a pull request to the documentation/recipes if you think it may be useful.

**Comment by jsocol** [comment]
@ibolit I definitely think that recipe would be a worthy inclusion as an example!

**Comment by jsocol** [comment]
Closing as stale, would still absolutely appreciate a PR with an example like this in the cookbook
