### ISSUE TITLE
Rate limit example with lambda rate is wrong

### ISSUE THREAD

**Issue by xrobin** [jsocol/django-ratelimit#182]
On page https://django-ratelimit.readthedocs.io/en/stable/usage.html#examples , in the examples, the following seems to be wrong:

    rate = lambda r: None if request.user.is_authenticated else '100/h'

Gave me a `TypeError: takes exactly 1 argument (2 given)`

I had to change it to:

    rate = lambda g, r: None if r.user.is_authenticated else '100/h'

and it worked fine.

**Comment by jsocol** [comment]
Ah we must have missed this back in #59 or so. Thanks for the heads up!
