### ISSUE TITLE
[master] usage.rst contains buggy lamba example?

### ISSUE THREAD

**Issue by hartwork** [jsocol/django-ratelimit#191]
At https://github.com/jsocol/django-ratelimit/blame/master/docs/usage.rst#L121 the docs read:
> rate = lambda g, r: None if request.user.is_authenticated else '100/h'

I believe it needs this patch:
```diff
--- rate = lambda g, r: None if request.user.is_authenticated else '100/h'
+++ rate = lambda g, r: None if       r.user.is_authenticated else '100/h'
```
Would you accept a pull request (with proper whitespace) about this?

**Comment by adamchainz** [comment]
Yes please make the PR!

**Comment by hartwork** [comment]
Here you go: #192
