### ISSUE TITLE
Updated primary branch to `main`

### ISSUE THREAD

**Issue by jsocol** [jsocol/django-ratelimit#199]
If you have a clone, from now on please use the `main` branch.

**Comment by benjaoming** [comment]
Can I ask what the reason for this is? There is still a `master` branch.

https://github.com/jsocol/django-ratelimit/compare/master...main

**Comment by jsocol** [comment]
The reason is that it’s a small but easy step toward making the open source world more inclusive. 

The reason I haven’t deleted the other branch yet is because it messed with PRs that we’re open

**Comment by adamchainz** [comment]
Btw, as I understand, GitHub will be coming out with a tool to alllow renaming of the primary branch, including retargetting PR's. We're holding off on Django's repos until that's available.

**Comment by benjaoming** [comment]
Ah cool, I didn't even think about terminology, I thought it was a new git workflow :)

Great initiative!

**Comment by adamchainz** [comment]
FYI: https://www.theregister.com/2020/06/15/github_replaces_master_with_main/ and http://www.kapwing.com/blog/how-to-rename-your-master-branch-to-main-in-git/

**Comment by jsocol** [comment]
@adamchainz Do you have anything newer than mid-June? I haven't seen anything official from GitHub. Only articles that all cite Nat's one tweet about it

**Comment by adamchainz** [comment]
Afraid I don't. On Django we decided at that time to wait. It seems GitHub got a lot of flak for the one tweet but I presume they'll still git around to it.

**Comment by adamchainz** [comment]
Just discovered this: https://github.com/github/renaming in this week's Django News

**Comment by jsocol** [comment]
Oh that's awesome, thank you! I think that's the first thing I've seen from GH in an official channel, so I'll probably hold off on changing repos where there are open PRs until they roll some of those out.
