### ISSUE TITLE
Custom Admin decorator broken with upgrade?

### ISSUE THREAD

**Issue by getup8** [jsocol/django-ratelimit#202]
Haven't had time to fully debug this so chance this is a red herring, but I didn't change anything in this implementation:

```python
class CustomAdminSite(admin.AdminSite):

    @never_cache
    @ratelimit(key='ip', rate='3/m', method=ratelimit.UNSAFE, block=True)
    @ratelimit(key='post:username', rate='3/m', method=ratelimit.UNSAFE, block=True)  # noqa
    def login(self, request, extra_context=None):
        return super(CustomAdminSite, self).login(request, extra_context)
```

And I'm getting the error:
```
AttributeError: 'CustomAdminSite' object has no attribute 'method'
(3 additional frame(s) were not displayed)
...
  File "django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "ratelimit/decorators.py", line 18, in _wrapped
    ratelimited = is_ratelimited(request=request, group=group, fn=fn,
  File "ratelimit/core.py", line 119, in is_ratelimited
    usage = get_usage(request, group, fn, key, rate, method, increment)
  File "ratelimit/core.py", line 135, in get_usage
    if not _method_match(request, method):
  File "ratelimit/core.py", line 72, in _method_match
    return request.method in [m.upper() for m in method]
```

Any advice?

As an aside, I imagine using this for the Django Admin is pretty common? Would be great to have an example in the docs.

**Comment by getup8** [comment]
I saw the release notes (sorry about that) for 3.0, but still running into difficulties.  This is the new implementation:

```python
    @method_decorator(never_cache)
    @method_decorator(ratelimit(key='ip', rate='3/m', method=ratelimit.UNSAFE, block=True))  # noqa
    @method_decorator(ratelimit(key='post:username', rate='3/m', method=ratelimit.UNSAFE, block=True))  # noqa
    def login(self, request, extra_context=None):
        """
        Override of Admin login so we can use ratelimit decorators.
        """
        return super(CustomAdminSite, self).login(request, extra_context)
```

Unfortunately, this is now blocking *everything*, it won't allow a single login attempt (at least testing locally).

**Comment by jsocol** [comment]
Hmm just to be sure, what are the local settings for `CACHES`, `RATELIMIT_USE_CACHE`, and `RATELIMIT_FAIL_OPEN`? Have you noticed issues on any other ratelimited views?

I’ve seen it block everything when there’s an issue reaching the cache and FAIL_OPEN is set to false (which is the default)

**Comment by getup8** [comment]
Thanks for the quick response! And yes you were right.. I hadn't started my Redis server locally so it wasn't connecting. Working great now thank you.

Still think a Django Admin example (maybe just mine from above) would be helpful in the docs!  And maybe a warning logged when the cache isn't reachable :)
