### ISSUE TITLE
 set my rate=1/d, i.e views should only work for one time in a day. but as i upload and try to convert image twice it still rendering the view, it should have given 403 error but its not giving

### ISSUE THREAD

**Issue by shubham17sm** [jsocol/django-ratelimit#205]
So for the above question answer i figure out that we need to put `block=True` in decorator. like this 
```@ratelimit(group='free',` key='user', rate=per_user, block=True)```
But the problem is when i kept rate=1/d  i.e. view should only render one time in one day. It worked at that time when i again try to access that view as it gave 403 error page. but when i checked the same thing after 5 min, the view was still rendering.(In per-user limiting)

**Comment by jsocol** [comment]
Thanks @shubham17sm, just so I'm sure I'm understanding right, you're getting:

```
request 1: allowed
request 2: allowed
request 3: denied
<wait 5 minutes>
request 4: allowed
```
?

Can you share the cache settings you're using when doing this test?

**Comment by shubham17sm** [comment]
I am getting:
```
request 1: allowed
request 2: denied
<wait 5 minutes>
request 3: allowed
request 4: denied

```
settings.py 
```
# RATELIMIT SETTINGS

RATELIMIT_ENABLE = True
RATELIMIT_USE_CACHE = 'default'
```

**Comment by jsocol** [comment]
This sounds familiar, probably related to the [default 300s timeout](https://docs.djangoproject.com/en/dev/ref/settings/#timeout). It should have been fixed in #112, so I'm curious why it might be recurring.

Can you share your `CACHES` setting, at least for the `default`?

**Comment by shubham17sm** [comment]
```
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
        'LOCATION': '127.0.0.1:11211',
    }
}

```

**Comment by jsocol** [comment]
Closing this out for now. @shubham17sm please reopen if you can provide more info. (Or anyone else who is also experiencing this on the latest version.)
