### ISSUE TITLE
Show and unblock IP's in Admin 

### ISSUE THREAD

**Issue by s7e7v7e7n7** [jsocol/django-ratelimit#213]
How can I see and ublock the IP addresses blocked with Ratelimit in admin? Is there a way to do this?

Thanks.

**Comment by adamchainz** [comment]
There's no way by default, since ratelimit uses Django's cache system to store rates, and the cache can't be easily queried. But you can build your own tracking on top if you call `is_ratelimited`. See also #210 which asked the same question.
