### ISSUE TITLE
Conflict with PyPI ratelimit

### ISSUE THREAD

**Issue by jayvdb** [jsocol/django-ratelimit#214]
https://github.com/tomasbasham/ratelimit also installs as `ratelimit`, creating a conflict.  ping @tomasbasham .

It appears as if this django module pre-dates the non-django module.

I wonder if the two sets of functionality might be able to be merged together, in a way that avoids breaking the APIs.

**Comment by jsocol** [comment]
Looking at @tomasbasham's library, I doubt these can or should be merged. They do things in very different ways for very different use cases.

In principle I'd be open to considering renaming this to `django_ratelimit` or similar. It's the most major of major upgrades, though, so I'd probably want to go through a deprecation step. And I'd also want to be sure that the target name is available so as not to repeat the problem.

Given how different the target situations for these libraries are, though, I wonder how big a deal this is in practice? If you're aiming for horizontally-scalable endpoint ratelimiting in a django app, it feels like in-process function ratelimiting is going to be less helpful—and vice versa.

**Comment by adamchainz** [comment]
It's for this reason that I always name my libraries `django_<thing>`

> It's the most major of major upgrades, though, so I'd probably want to go through a deprecation step.

We could rename to `django_ratelimit` and ship an import shim for a few months with something like:

```python
# ratelimit.py
import warnings
warnings.warn('import from django_ratelimit instead, DeprecationWarning)
from django_ratelimit import *  # more imports may be needed
```

**Comment by jsocol** [comment]
Oh I would now for sure, but 10 years ago me didn't really understand the value of namespacing yet.

But yeah that kind of import shim was basically what I was thinking. It doesn't even have to be a few months, really, could do something like ship 3.1 (import shim) and 4.0 (no shim) at the same time to facilitate moving. Or maybe 4.0b to avoid breaking things for folks who specified `>=3` instead of `>=3,<4`

**Comment by jayvdb** [comment]
IMO you can keep the shim indefinitely, especially if there is an sdist on PyPI, possibly with an setup.py conditionally including the shim only if there is no existing use of the old name at install time.  i.e. ppl needing the shim can get it by forcing pip to use the v4 sdist, while the v4 wheel only provides the new name.  pip's conditional sdist vs wheel selection functionality is now advanced enough that this is a reasonable approach, and the only people likely to be needing it long term, are implementors threading needles through various bits of old software to keep an old system hanging together for a bit longer.

My use case is distro packaging, where the two "need" to be distinct even though they may never be used concurrently (or use "Conflicts:" to prevent the two being concurrently installed on the same image, but that still has some downsides).  A distro packager can simply forcefully remove the shim from their package, and patch any other software that is still using the old name.
