### ISSUE TITLE
Next release from v3.0.1

### ISSUE THREAD

**Issue by Andrew-Chen-Wang** [jsocol/django-ratelimit#240]
Hey @jsocol when do you think another release can come out? It seems like the name changing would cause a huge breakage, but also lots of features have been added. Any plans?

**Comment by PeterJCLaw** [comment]
@jsocol just wondering if there's anything that contributors can help with here towards getting out a release? (cc @adamchainz, appreciate you're busy though)

**Comment by benjaoming** [comment]
If it's a lot of work to verify the next release, a pre-release that we can verify together would also work?

**Comment by jsocol** [comment]
v4 has been out for a while and I'm putting v4.1 out now. Hopefully that helps here!
