### ISSUE TITLE
What am I doing wrong?

### ISSUE THREAD

**Issue by SHxKM** [jsocol/django-ratelimit#246]
I'm using `django-ratelimit` (so elegantly designed, thanks contributors!) to ratelimit some naughty RSS feed aggregators:

Here's a code snippet:

```
class PersonalRSSFeed(Feed):
    link = "/feeds/"
    description_template = "personal_rss_feed.html"

    @method_decorator(ratelimit(key="header:path-info", rate="3/m", method="GET"))
    @method_decorator(ratelimit(key="header:path-info", rate="1/s", method="GET"))
    def __call__(self, request: WSGIRequest, *args: Any, **kwargs: Any) -> HttpResponse:
        if request.limited:  # request.limited is injected by django-ratelimit
            logger.warning(
                f"RATELIMIT ::: RSS ::: path: {request.META.get('PATH_INFO')}"
            )
            return HttpResponse(RATELIMITED_MESSAGE, status=429)
        return super().__call__(request, *args, **kwargs)
```

In `request.META["PATH_INFO"]` I should always get strings like these:

```
users/feeds/some-uuid-1/
users/feeds/some-uuid-2/
users/feeds/some-uuid-3/
```

Where each `UUID` identifies a different user.

Am I right that `key` here should differentiate between users? Because in production (where there are many different users and calls to the different paths) I'm getting rate-limits way too often considering the my decorators' settings.

As I understand it `key` identifies the potentially rate-limited "entity", and `group` allows us to "bin" different rate limits by group, but if the `group` is the same and the `key` is different then they shouldn't share the same rate-limit.

What am I doing wrong?

**Comment by SHxKM** [comment]
OK, it seems that `header:` always assumes the property is going to start with `HTTP_` and therefore all my users are sharing the same key.

**Comment by jsocol** [comment]
Ah yeah, `PATH_INFO` isn't technically a header—like a lot of stuff in `request.META`; you can see some of this discussion on https://github.com/jsocol/django-ratelimit/pull/208#issuecomment-678833865. All the request headers do get the `HTTP_` prefix, hence the behavior of `key='header:*'`.
