### ISSUE TITLE
I installed the version 3.0.1. But still when I explored the ratelimit package in my virtualenv, it still has utils.py and __init__ has version 2.0.0?

### ISSUE THREAD

**Issue by anveshagarwal** [jsocol/django-ratelimit#252]

**Comment by adamchainz** [comment]
It sounds like you didn't actually install correctly. Try with `venv/bin/python -m pip install django-ratelimit`

**Comment by anveshagarwal** [comment]
The version in `__init__` is fixed now and code is of latest 3.0.1 version. But `utils.py` is still there in the downloaded folder. So I can import `is_ratelimited` from it also.

**Comment by adamchainz** [comment]
I'm afraid it seems like the issue is all in your enviornment. And it's too hard to debug what's wrong with your Python installation or virtual environment through an issue chat.

I would try deleting and rebuilding your virtual environment, being careful to use `python -m pip` to avoid mixing up Python/pip versions.

**Comment by anveshagarwal** [comment]
I tried to reproduce this behaviour in a python:3.7 docker instance. (for platform independence)
1. Run python 3.7 docker image with shell access: `sudo docker run -it --entrypoint /bin/bash python:3.7`
2. create a virtualenv : `python -m venv venv`
3. activate env: `source venv/bin/activate`
4. install django-ratelimit: `pip install django-ratelimit==3.0.1`
5. Now browse to the ratelimit package in env: `cd /venv/lib/python3.7/site-packages/ratelimit/`

Here you will find the list of files which are: __init__.py  __pycache__  core.py  decorators.py  exceptions.py  middleware.py	mixins.py  models.py  tests.py	utils.py

I hope it may help to reproduce.
