### ISSUE TITLE
Wrong project link on pypi

### ISSUE THREAD

**Issue by smoehrle** [jsocol/django-ratelimit#279]
Hey,

on the [pypi page](https://pypi.org/project/django-ratelimit/) of this package the project link is misconfigured. It points to [pystatsd](https://github.com/jsocol/pystatsd).

I noticed this because renovate-bot shows the wrong changelog for the new 4.0.0 version :robot:

**Comment by benjaoming** [comment]
It's been fixed but the fix is not released: https://github.com/jsocol/django-ratelimit/commit/583ce7670b0c6fc4faf761d53d242b6e09c688e3

**Comment by benjaoming** [comment]
> I noticed this because renovate-bot shows the wrong changelog for the new 4.0.0 version :robot:

Funny implication :)

**Comment by mlissner** [comment]
Yeah, a few months later and dependabot has the same issue of showing the wrong links. Example here if curious: https://github.com/freelawproject/courtlistener/pull/2561

**Comment by jsocol** [comment]
Fixed in v4.1.0. Thanks for flagging!
