### ISSUE TITLE
Incorrect homepage link on PyPI

### ISSUE THREAD

**Issue by PeterJCLaw** [jsocol/django-ratelimit#290]
The "Homepage" link in the published packages (e.g: at https://pypi.org/project/django-ratelimit/4.0.0/) seems to https://github.com/jsocol/pystatsd, which seems wrong.

**Comment by benjaoming** [comment]
This is already fixed here: https://github.com/jsocol/django-ratelimit/commit/583ce7670b0c6fc4faf761d53d242b6e09c688e3

Once the next release is out, the URL will be updated

**Comment by jsocol** [comment]
Fixed in v4.1. Thanks for flagging!
