### ISSUE TITLE
Drop `compat.get_caches`, use new `caches` api

### ISSUE THREAD

**Issue by bitcity** [jsocol/django-ratelimit#43]
Leaving a note for future change: 

Django 1.7 has deprecated [`get_cache`](https://docs.djangoproject.com/en/dev/topics/cache/#django.core.cache.get_cache) in favor of [`caches`](https://docs.djangoproject.com/en/dev/topics/cache/#django.core.cache.caches)

This [line here](https://github.com/jsocol/django-ratelimit/blob/master/ratelimit/helpers.py#L5) would need a change sometime in the near future.

**Comment by jbinney** [comment]
@jsocol looks like @carljm fixed this in https://github.com/jsocol/django-ratelimit/commit/44147a580dedb688abbe6c867b03d35f384d1765

**Comment by jsocol** [comment]
At this point I'm gonna leave this around to drop `compat.get_caches`

**Comment by claudep** [comment]
Looks like this was fixed by 5e357082135e

**Comment by jsocol** [comment]
Yep! Thanks for the note :)
