### ISSUE TITLE
is_ratelimited is broken if group is None and fn  is None

### ISSUE THREAD

**Issue by carlshimer** [jsocol/django-ratelimit#53]
subject says it all.  The docs don't indicate that one or the other is required.  Will crash on try to look for **module** on fn which is null.

<pre>
  if group is None:
        if hasattr(fn, '__self__'):
            parts = fn.__module__, fn.__self__.__class__.__name__, fn.__name__
        else:
            parts = (fn.__module__, fn.__name__)
        group = '.'.join(parts)
</pre>

**Comment by jplehmann** [comment]
I was confused by this as well.  Since the decorator appears to accept `=None` as an argument, it implies to me that `is_ratelimited` should as well (unless specified).

**Comment by tapionx** [comment]
i stepped into this problem too
