### ISSUE TITLE
key callable only takes one argument but docs say two

### ISSUE THREAD

**Issue by pmclanahan** [jsocol/django-ratelimit#58]
Actually it looks like a callable passed in is only passed the request, but a dotted string which results in a callable is passed the group also. I thought the docs were wrong, but maybe it's the fact that a callable is only being passed a single argument. Perhaps for backward compatibility you can accept an alternate second param and shuffle if it remains `None`.

I should have a PR shortly with a recommendation.

**Comment by pmclanahan** [comment]
Ha! That was a silly recommendation after looking at the code again. It'll have to be an inspection of the function... tricky and maybe not worth it?

**Comment by jsocol** [comment]
aha, [line 134](https://github.com/jsocol/django-ratelimit/blob/master/ratelimit/utils.py#L134) should look like line 145. This is an error and I don't want to support backwards compat here.

**Comment by pmclanahan** [comment]
Easier to fix then :) Was going with:

```python
        try:
            value = key(group, request)
        except TypeError:
            value = key(request)
```

But if you don't want, I'll submit simpler PR.

**Comment by jsocol** [comment]
Yeah, just need to document the change. It should only work right.

**Comment by pmclanahan** [comment]
Will this be in `0.6`? I'll add a versionchanged note.

**Comment by jsocol** [comment]
Yep.

**Comment by bitcity** [comment]
What's the ETA for 0.6 ?
