### ISSUE TITLE
Deprecated importlib module and deprecated get_cache

### ISSUE THREAD

**Issue by SimonSteinberger** [jsocol/django-ratelimit#60]
Django's importlib module will be removed with the next version (1.9).
Also, 'get_cache' is deprecated in favor of 'caches'.

Please replace in utils.py:

> from django.utils.importlib import import_module

With the Python importlib:

> from importlib import import_module

You can modify the get_cache import like that, so it works with all Django versions:

> try:
> ----from django.core.cache import caches
> except:
> ----from django.core.cache import get_cache as caches

Then load the cache like so:

> cache = hasattr(caches, '__call__') and caches(cache_name) or caches[cache_name]

Wonderful tool by the way! Thank you :-)

**Comment by jieter** [comment]
Just updated to 1.8 and got the warnings too, would be nice if these will be fixed.

**Comment by jsocol** [comment]
Fixed by #70
