### ISSUE TITLE
Limit per parameter

### ISSUE THREAD

**Issue by anishmenon** [jsocol/django-ratelimit#69]
i've a url 

mydomain.com/contactme?email='sssss@cccc.com'

@ratelimit(rate='5/m',block=True,field='email', method=['GET'])
def contactme(request):
    retrurn pass

when i hit simply hit 

mydomain.com/contactme

y its blocking after 5 attempts per minute . There is no parameter 'email' . Only need to block when the same email value for parameter email 5/min

**Comment by willkg** [comment]
It's probably worth upgrading to 0.5.0 which simplified the `ratelimit` decorator significantly.

http://django-ratelimit.readthedocs.org/en/stable/usage.html#ratelimit

That uses a `key` argument and the value you'd want is probably something like `get:email`.

**Comment by jsocol** [comment]
You could also use a [callable `rate`](http://django-ratelimit.readthedocs.org/en/stable/rates.html#callables), and have it `if 'email' not in request.GET: return None` to indicate "no limit"

**Comment by jsocol** [comment]
I'm closing this because while that behavior should be supported—and is, via the callables, or using `is_ratelimited`—it shouldn't be the default that you can bypass ratelimiting by omitting parameters. That fails at the primary goal of protecting infrastructure.

**Comment by anishmenon** [comment]
Thanks for all comments
