### ISSUE TITLE
Question on example in docs

### ISSUE THREAD

**Issue by bitcity** [jsocol/django-ratelimit#71]
I'm looking at the [usage examples](https://django-ratelimit.readthedocs.org/en/latest/usage.html) in docs, 

The one below says `if same username OR IP is used ...` , Shouldn't this be just username (no IP address) ?

    @ratelimit(key='post:username', rate='5/m', method=['GET', 'POST'])
    def login(request):
        # If the same username OR IP is used >5 times/min, this will be True.
        # The `username` value will come from GET or POST, determined by the
        # request method.
        was_limited = getattr(request, 'limited', False)
        return HttpResponse()

**Comment by jsocol** [comment]
Yep, you're right, that's a typo in the docs. That's supposed to have another stacked decorator with `key='ip'`
