### ISSUE TITLE
django.utils.importlib deprecated

### ISSUE THREAD

**Issue by tayden** [jsocol/django-ratelimit#75]
Getting warning:

    C:\...\ratelimit\utils.py:9: RemovedInDjango19Warning:
    django.utils.importlib will be removed in Django 1.9.
        from django.utils.importlib import import_module

My understanding is that this should just be changed to `from importlib import import_module`

[Relevant docs link](https://docs.djangoproject.com/en/1.8/releases/1.7/#django-utils-dictconfig-django-utils-importlib)

**Comment by jsocol** [comment]
Please update to v0.6.0, which has this fixed:




https://github.com/jsocol/django-ratelimit/blob/master/ratelimit/compat.py




--
