### ISSUE TITLE
A new release?

### ISSUE THREAD

**Issue by SevenDeadlySins** [jsocol/django-ratelimit#99]
Now that Django 1.9 is out, it'd be nice to have an official release that supports it, so that we don't have to pull from repo in order to use this with Django 1.9. Any way that can happen?

**Comment by jsocol** [comment]
Oof, I didn't realize it had been so long, there's [kind of a lot](https://github.com/jsocol/django-ratelimit/compare/v0.6.0...master) in this release.

I'll take a look this week and see what's there, if there's any follow up that _needs_ to be in, and what else is currently open that needs to happen, or what can be pushed. I know there's a least one documentation issue @willkg and I talked about that I absolutely want to get fixed.

**Comment by SevenDeadlySins** [comment]
That's reasonable. My main thing is just that I'm looking to update to 1.9 at my workplace, and this package not being compatible with 1.9 in an official release is a problem.

Thanks for getting back to me- hopefully it's not too much of a problem to get an official release out.

**Comment by upwell** [comment]
Also waiting for the official release to support Django 1.9. Thanks for your hard work, @jsocol. This module is great.

**Comment by seanthegeek** [comment]
In the meantime, you can add `git+https://github.com/jsocol/django-ratelimit` using pip/requirements.txt to get the latest version from this repo.

**Comment by mrcoles** [comment]
Just checking in to see what’s potentially left in getting a pypi release with django 1.9 support? Or are there some dangling tasks?

**Comment by claudep** [comment]
@jsocol Any help needed before releasing?

**Comment by heyyeah** [comment]
@jsocol let us know if you need help with testing for release

**Comment by jsocol** [comment]
1.0 is out! https://pypi.python.org/pypi/django-ratelimit/1.0.0 It supports Django 1.8 and up.

**Comment by jsocol** [comment]
Thanks for all the help/offers here, folks! Sorry I'm not the fastest maintainer these days

**Comment by claudep** [comment]
Great, thanks for your time!
